id: A1C314FF4
title: Guru Yoga of the Great Tertön Pema Lingpa
type: translation
pechas:
- I4896C61A
- I41F0D9F1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:48.307849
  last_modified_at: 2023-01-04 12:12:48.307863
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I4896C61A/5EED: 381B
  I41F0D9F1/A9E3: 381B
